CREATe TABLE "person"("id" SERIAL8  PRIMARY KEY UNIQUE,"name" VARCHAR NOT NULL,"age" INT8 NULL);
CREATe TABLE "blog_post"("id" SERIAL8  PRIMARY KEY UNIQUE,"title" VARCHAR NOT NULL,"body" VARCHAR NOT NULL);
